

```{r}
library(ggplot2)
library(patchwork)
library(tidyr)
library(survival)
library(mvtnorm)
library(lubridate)
library(survival)
library(survminer)
library(rpact)
library(dplyr)
library(Hmisc)
library(coxed)
library(gtsummary)
library(gsDesign)
library(dplyr)
library(MDBED)
library(RColorBrewer)
```

# SAMPLE SIZE (Fixed)

```{r, echo=FALSE, warning = FALSE}
# Inputs
zb <- -0.84        # Z-score for power (e.g., 80% power)
za <- -1.645       # Z-score for significance level (e.g., alpha = 0.05)
HR1 <- 1      
HR0 =  1.25  # Hazard ratio under alternative hypothesis
#m   = 0.3           # non-inferiority margin
pi <- 0.5         # Allocation ratio (e.g., 1:1 randomization)
pa=1             # probability of NOT censoring in arm A
pb=1           # probability of NOT censoring in arm B

A = (za+zb)^2 
B= log(HR0)^2*pi*(1-pi)

E=ceiling(A/B)
E
```

# POWER LOSS - THEORETICAL 

### GSD, interim at IF=50%

```{r, echo=FALSE, warning = FALSE}

time=0.5
x=gsDesign(k = 2, test.type = 1, n.fix = E, beta = 0.2, alpha = 0.05, sfu = sfLDOF, timing = c(time,1)) 
x
za1=x$upper$bound[1]
E1=ceiling(x$n.I[1])
za2=x$upper$bound[2]
E2=ceiling(x$n.I[2])
```

```{r, echo=FALSE, warning = FALSE}

fi =seq(1,4,0.1)
pi=fi/(fi+1)

zb1=sqrt(E1 * (log(HR0)^2) * pi * (1 - pi)) - za1

delta1=(za1+zb1)/sqrt(E1)

power1=pnorm(za1-delta1*sqrt(E1),0,1, lower.tail = F)#h1

##################################################

zb2=sqrt(E2 * (log(HR0)^2) * pi * (1 - pi)) - za2

delta2=(za2+zb2)/sqrt(E2)

power2=rep(0,length(delta1))
for (i in 1:length(delta1)) {
    

mu <- c(0, 0)  # Mean vector
sigma <- matrix(c(1, (sqrt(E1)/sqrt(E2)), (sqrt(E1)/sqrt(E2)),1), ncol = 2)  # Covariance matrix

# Bounds
lower <- c(-Inf, za2-delta2[i]*sqrt(E2))  # Lower limits
upper <- c(za1-delta1[i]*sqrt(E1), Inf)        # Upper limits

# Compute the integral
prob <- pmvnorm(lower = lower, upper = upper, mean = mu, sigma = sigma)
power2[i]=prob[1]
}

##############################################

power_tot=round(power1+power2,4)

d=as.data.frame(cbind( ceiling(E1),  ceiling(E2)-ceiling(E1), round(pi,4), round(power1,6), round(power2,4), power_tot))#,E_increase

names(d)=c( "E1", "E2","p",  "Power 1", "Power 2", "Power overall")
print(d)
```


```{r, echo=FALSE, warning = FALSE}
# Reshape the dataset d to long format for ggplot
d_long <- d %>%
  pivot_longer(cols = c("Power 1", "Power 2", "Power overall"),
               names_to = "Power_Type",
               values_to = "Value")

# Set color palette (same as in plot1)
colors <- brewer.pal(n = 12, name = "Paired")[1:length(unique(d_long$Power_Type))]

# Create the plot
g <- ggplot(d_long, aes(x = p, y = Value, color = Power_Type)) +
  geom_line(size = 1.2) +  # Thicker lines for readability
  geom_point(size = 2) +
  coord_cartesian(ylim = c(0.1, 0.85)) + 
  scale_y_continuous(breaks = seq(0, 1, by = 0.1)) +
  scale_color_manual(values = colors) +
  labs(title = "",
       x =  expression(pi[E]),
       y = "",
       color = "") +
  theme_minimal(base_size = 12) +  # Larger text for publication
  theme(legend.position = "bottom",
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 10),
        plot.title = element_text(face = "bold", size = 12),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 12))

# Print the plot
g

cairo_pdf("Figure3_fixed.pdf", width = 10, height = 7, family = "DejaVu Sans")
plot(g)   # your plotting code
dev.off()

```


